import Sidebar from "../components/sidebar";
import "./globals.css";
import { Gothic_A1 } from "next/font/google";
import clsx from "clsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gothic_A1 = Gothic_A1({
  weight: ["400", "700"],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={clsx("container mt-28 mx-auto max-w-4xl flex gap-x-5", gothic_A1.className)}>
          <Sidebar />
          <div className="min-w-0 mt-6 md:mt-0 gap-y-5 flex flex-col px-2 md:px-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
